# Generated by Django 5.2.4 on 2025-08-03 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='title',
            field=models.CharField(default='titulo generico', max_length=100),
            preserve_default=False,
        ),
    ]
